"""
store.py — DB CRUD for repo_index, repo_commits, repo_hunks, repo_incidents.

# OWNS: row-level reads/writes for the four hosted-index tables.
# NOT OWNS: schema (migration 0065), vector storage (core/vector_store.py),
#           git walking (ingest.py).
#
# INVARIANTS:
#   * repo_id is generated by upsert_repo (uuid4 hex) — never trusted from caller.
#   * All timestamps written as ISO-8601 UTC 'Z'-suffixed strings (matches
#     existing core/jobs/db.py convention so cross-table joins parse uniformly).
#   * Hunk IDs are deterministic sha256(repo_id || commit_sha || file || idx)
#     so re-ingest is idempotent.
#   * vector_entries removal is the caller's responsibility — store.py only
#     manages the metadata rows. delete_repo() coordinates the vector cleanup.
"""

from __future__ import annotations

import hashlib
import json
import logging
import uuid
from datetime import datetime, timezone

from core import db as _db
from core import vector_store as _vs
from core.hosted_index.types import CommitMeta, IngestStatus

_LOG = logging.getLogger(__name__)


def _now_iso() -> str:
    """Pure: UTC ISO-8601 'Z'-suffixed."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _repo_namespace(repo_id: str) -> str:
    """Pure: vector_store namespace for a repo's hunks."""
    return f"repo:{repo_id}"


def hunk_id_for(repo_id: str, commit_sha: str, file: str, hunk_idx: int) -> str:
    """Pure: deterministic hunk_id so re-ingest is idempotent.

    Why deterministic: ingesting the same commit twice should overwrite the
    same row, not insert a duplicate. The natural key is the
    (repo, commit, file, position) tuple; sha256 keeps it compact and
    URL-safe.
    """
    raw = f"{repo_id}|{commit_sha}|{file}|{hunk_idx}".encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


# ---------------------------------------------------------------------------
# repo_index
# ---------------------------------------------------------------------------


def upsert_repo(owner_id: str, url: str, repo_id: str | None = None) -> str:
    """Create or return an existing repo_index row. Returns repo_id.

    Why upsert and not insert-only: re-running an ingest for the same
    (owner, url) pair should be idempotent — same row, status reset to
    pending. Callers don't need to pre-check.
    """
    if not isinstance(owner_id, str) or not owner_id.strip():
        raise ValueError("owner_id must be a non-empty string")
    if not isinstance(url, str) or not url.strip():
        raise ValueError("url must be a non-empty string")

    now = _now_iso()
    with _db.get_db_connection() as conn:
        with conn:
            existing = conn.execute(
                "SELECT repo_id FROM repo_index WHERE owner_id = %s AND url = %s",
                (owner_id, url),
            ).fetchone()
            if existing is not None:
                rid = existing["repo_id"]
                # Reset status so a fresh ingest can proceed cleanly.
                conn.execute(
                    "UPDATE repo_index SET status = %s WHERE repo_id = %s",
                    (IngestStatus.PENDING.value, rid),
                )
                return rid
            rid = repo_id or uuid.uuid4().hex
            conn.execute(
                "INSERT INTO repo_index "
                "(repo_id, owner_id, url, status, created_at) "
                "VALUES (%s, %s, %s, %s, %s)",
                (rid, owner_id, url, IngestStatus.PENDING.value, now),
            )
    return rid


def mark_repo_status(repo_id: str, status: IngestStatus, head_sha: str | None = None) -> None:
    """Update status (and optionally head_sha + last_ingested_at) atomically."""
    if not isinstance(status, IngestStatus):
        raise TypeError(f"status must be IngestStatus, got {type(status).__name__}")
    now = _now_iso()
    with _db.get_db_connection() as conn:
        with conn:
            if head_sha is None:
                conn.execute(
                    "UPDATE repo_index SET status = %s WHERE repo_id = %s",
                    (status.value, repo_id),
                )
            else:
                conn.execute(
                    "UPDATE repo_index "
                    "SET status = %s, head_sha = %s, last_ingested_at = %s "
                    "WHERE repo_id = %s",
                    (status.value, head_sha, now, repo_id),
                )


def get_repo(repo_id: str) -> dict | None:
    """Return the repo_index row as a dict, or None if absent."""
    with _db.get_db_connection() as conn:
        row = conn.execute(
            "SELECT * FROM repo_index WHERE repo_id = %s",
            (repo_id,),
        ).fetchone()
    return row


def delete_repo(repo_id: str) -> int:
    """Remove every row in every hosted-index table for repo_id, including vectors.

    Returns the total deleted-row count across all tables (useful for tests).
    """
    deleted = 0
    namespace = _repo_namespace(repo_id)
    with _db.get_db_connection() as conn:
        with conn:
            for table in ("repo_hunks", "repo_commits", "repo_incidents", "repo_index"):
                cur = conn.execute(
                    f"DELETE FROM {table} WHERE repo_id = %s",
                    (repo_id,),
                )
                deleted += cur.rowcount
    # Vector entries live in their own table; delete via the public API to
    # keep the upgrade path (pgvector) transparent.
    deleted += _vs.delete_namespace(namespace)
    return deleted


# ---------------------------------------------------------------------------
# repo_commits
# ---------------------------------------------------------------------------


def upsert_commit(meta: CommitMeta) -> None:
    """Insert or update a commit row. Idempotent on (repo_id, commit_sha)."""
    if _db.IS_POSTGRES:
        sql = (
            "INSERT INTO repo_commits "
            "(commit_sha, repo_id, parent_sha, author, ts, was_reverted, hotfix_for) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (repo_id, commit_sha) DO UPDATE SET "
            "parent_sha = EXCLUDED.parent_sha, "
            "author = EXCLUDED.author, "
            "ts = EXCLUDED.ts, "
            "was_reverted = EXCLUDED.was_reverted, "
            "hotfix_for = EXCLUDED.hotfix_for"
        )
    else:
        sql = (
            "INSERT OR REPLACE INTO repo_commits "
            "(commit_sha, repo_id, parent_sha, author, ts, was_reverted, hotfix_for) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s)"
        )
    with _db.get_db_connection() as conn:
        with conn:
            conn.execute(
                sql,
                (
                    meta.commit_sha,
                    meta.repo_id,
                    meta.parent_sha,
                    meta.author,
                    meta.ts,
                    1 if meta.was_reverted else 0,
                    meta.hotfix_for,
                ),
            )


def get_commit(repo_id: str, commit_sha: str) -> dict | None:
    """Fetch a commit row, or None if absent."""
    with _db.get_db_connection() as conn:
        return conn.execute(
            "SELECT * FROM repo_commits WHERE repo_id = %s AND commit_sha = %s",
            (repo_id, commit_sha),
        ).fetchone()


def list_hotfix_commits_for(repo_id: str, suspect_commit_sha: str) -> list[dict]:
    """Return every commit row whose hotfix_for == suspect_commit_sha.

    Used by judge.did_this_change_cause_a_bug: a non-empty list is direct
    evidence that the suspect commit was followed by a fix.
    """
    with _db.get_db_connection() as conn:
        return conn.execute(
            "SELECT * FROM repo_commits "
            "WHERE repo_id = %s AND hotfix_for = %s "
            "ORDER BY ts ASC",
            (repo_id, suspect_commit_sha),
        ).fetchall()


def commit_count(repo_id: str) -> int:
    """Return how many commits are indexed for repo_id."""
    with _db.get_db_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS c FROM repo_commits WHERE repo_id = %s",
            (repo_id,),
        ).fetchone()
    return int(row["c"]) if row else 0


# ---------------------------------------------------------------------------
# repo_hunks
# ---------------------------------------------------------------------------


def upsert_hunk(
    repo_id: str,
    commit_sha: str,
    file: str,
    hunk_idx: int,
    ast_shape_hash: str | None,
    vector_entry_id: str,
) -> str:
    """Insert or update a hunk row. Returns the hunk_id."""
    hid = hunk_id_for(repo_id, commit_sha, file, hunk_idx)
    if _db.IS_POSTGRES:
        sql = (
            "INSERT INTO repo_hunks "
            "(hunk_id, commit_sha, repo_id, file, ast_shape_hash, vector_entry_id) "
            "VALUES (%s, %s, %s, %s, %s, %s) "
            "ON CONFLICT (hunk_id) DO UPDATE SET "
            "commit_sha = EXCLUDED.commit_sha, "
            "file = EXCLUDED.file, "
            "ast_shape_hash = EXCLUDED.ast_shape_hash, "
            "vector_entry_id = EXCLUDED.vector_entry_id"
        )
    else:
        sql = (
            "INSERT OR REPLACE INTO repo_hunks "
            "(hunk_id, commit_sha, repo_id, file, ast_shape_hash, vector_entry_id) "
            "VALUES (%s, %s, %s, %s, %s, %s)"
        )
    with _db.get_db_connection() as conn:
        with conn:
            conn.execute(
                sql, (hid, commit_sha, repo_id, file, ast_shape_hash, vector_entry_id),
            )
    return hid


def get_hunk(hunk_id: str) -> dict | None:
    """Fetch a hunk row, or None if absent."""
    with _db.get_db_connection() as conn:
        return conn.execute(
            "SELECT * FROM repo_hunks WHERE hunk_id = %s", (hunk_id,),
        ).fetchone()


def hunk_count(repo_id: str) -> int:
    """Return how many hunks are indexed for repo_id."""
    with _db.get_db_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS c FROM repo_hunks WHERE repo_id = %s",
            (repo_id,),
        ).fetchone()
    return int(row["c"]) if row else 0


# ---------------------------------------------------------------------------
# repo_incidents (optional — used by judge for stronger bug signal)
# ---------------------------------------------------------------------------


def add_incident(
    repo_id: str,
    summary: str,
    linked_commits: list[str],
    incident_id: str | None = None,
    ts: str | None = None,
) -> str:
    """Record a customer-supplied incident with linked commits.

    Why exposed: D-family agents like D16 Codebase Reviewer get stronger
    bug-signal evidence when the customer labels past incidents. The
    table accepts inputs from a separate /repo/incidents POST endpoint
    (not in this PR; consumer surface).
    """
    if not isinstance(linked_commits, list):
        raise ValueError("linked_commits must be a list of commit SHAs")
    iid = incident_id or uuid.uuid4().hex
    when = ts or _now_iso()
    payload = json.dumps(linked_commits, sort_keys=True, separators=(",", ":"))
    with _db.get_db_connection() as conn:
        with conn:
            conn.execute(
                "INSERT INTO repo_incidents "
                "(incident_id, repo_id, ts, summary, linked_commits) "
                "VALUES (%s, %s, %s, %s, %s)",
                (iid, repo_id, when, summary, payload),
            )
    return iid


def incidents_referencing(repo_id: str, commit_sha: str) -> list[dict]:
    """Return every incident whose linked_commits contains commit_sha.

    Uses a simple substring match on the JSON blob (no JSONB on SQLite).
    Acceptable at v0 scales (≤ low-thousands incidents per repo); if a
    customer's incident count grows past that, push the index into the
    relational layer.
    """
    with _db.get_db_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM repo_incidents WHERE repo_id = %s "
            "ORDER BY ts DESC",
            (repo_id,),
        ).fetchall()
    out: list[dict] = []
    for row in rows:
        try:
            linked = json.loads(row["linked_commits"] or "[]")
        except (TypeError, ValueError):
            continue
        if commit_sha in linked:
            out.append(row)
    return out
