ALTER TABLE agents ADD COLUMN pii_safe INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN outputs_not_stored INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN audit_logged INTEGER NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN region_locked TEXT;
